"""Validate the public inventory and generate its offline Markdown overview.

repositories.yaml deliberately uses JSON syntax, a YAML subset, so this tool
needs only Python's standard library. It performs no network requests.
"""
import argparse
import datetime
import json
from pathlib import Path
import re
import sys


def validate(data):
    """Reject unpublished/unverified entries and ambiguous observation states."""
    def require(condition, message):
        if not condition:
            raise ValueError(message)

    def dated(value):
        try:
            return datetime.datetime.fromisoformat(value).tzinfo is not None
        except (ValueError, TypeError):
            return False

    def url(value):
        return isinstance(value, str) and value.startswith(('https://github.com/', 'https://api.github.com/'))

    require(data.get('schema_version') == 1, 'Unsupported schema_version')
    sources = {source['id'] for source in data['sources']}
    require(len(sources) == len(data['sources']), 'Duplicate source IDs')
    for source in data['sources']:
        require(url(source['url']), 'Source must have GitHub evidence')
        datetime.date.fromisoformat(source['observed_date'])
    names = set()
    for repo in data['repositories']:
        name = repo['repository']
        require(re.fullmatch(r'basher83/[A-Za-z0-9_.-]+', name), 'Invalid repository name')
        require(name not in names, 'Duplicate repository')
        names.add(name)
        visibility = repo['visibility']
        require(visibility['value'] == 'public', f'{name}: only verified public repositories may be published')
        require(dated(visibility['observed_at']) and url(visibility['evidence']), f'{name}: visibility evidence/date required')
        observed = repo['observation']
        require(re.fullmatch(r'[a-f0-9]{40}', observed['revision'] or ''), f'{name}: immutable revision required')
        require(dated(observed['observed_at']) and url(observed['evidence']), f'{name}: observation evidence/date required')
        require(repo['purpose']['source'] in sources, f'{name}: unknown purpose source')
        require(repo['purpose']['basis'] in ('historical_card_description', 'inferred_from_readme_or_name'), f'{name}: explicit purpose qualifier required')
        datetime.date.fromisoformat(repo['purpose']['observed_date'])
        require(isinstance(repo['fork'], bool) and isinstance(repo['lifecycle']['archived'], bool), f'{name}: lifecycle/fork flags required')
        ci = repo['ci']
        require(ci['state'] in ('observed', 'unknown'), f'{name}: invalid CI state')
        require(ci['state'] != 'unknown' or ci['pr_workflow_declarations'] is None, f'{name}: unknown CI cannot assert PR coverage')
        require(ci['pr_workflow_declarations'] in (True, False, None), f'{name}: invalid PR declaration')
        for workflow in ci['workflows']:
            require(url(workflow['evidence']) and observed['revision'] in workflow['evidence'], f'{name}: workflow evidence must be pinned')
        required = repo['required_checks']
        require(required['state'] in ('observed', 'unknown'), f'{name}: invalid required-check state')
        require(bool(required['evidence']) and all(url(e) for e in required['evidence']), f'{name}: required-check evidence missing')
        if required['state'] == 'unknown':
            require(required['checks'] is None and bool(required.get('reason')), f'{name}: unknown checks need null plus reason')
        else:
            require(isinstance(required['checks'], list), f'{name}: observed checks need a list (empty means none)')
        require(repo['renovate']['state'] in ('observed', 'absent', 'unknown'), f'{name}: invalid Renovate state')
        require(isinstance(repo['unknowns'], list), f'{name}: explicit unknowns required')
    scope = data['scope']
    require(scope['public_count'] == len(names), 'Public count mismatch')
    require(scope['historical_card_count'] == scope['public_count'] + scope['excluded_count'], 'Scope counts do not reconcile')
    for entry in data['proposals'] + data['historical_observations']:
        require(entry['repository'] in names, 'Proposal/history references an excluded repository')
    return data


def cell(value):
    return str(value).replace('|', r'\|').replace('\n', ' ')


def required_label(repo):
    checks = repo['required_checks']
    if checks['state'] == 'unknown':
        return 'unknown'
    return ', '.join(checks['checks']) or 'none'


def render(data):
    """Render stable ordering with no clock, network or runtime assumptions."""
    repos = sorted(data['repositories'], key=lambda r: r['repository'].casefold())
    scope = data['scope']
    visibility_dates = sorted({r["visibility"]["observed_at"][:10] for r in repos})
    visibility_period = " to ".join(dict.fromkeys([visibility_dates[0], visibility_dates[-1]]))
    lines = [
        '<!-- Generated by portfolio/inventory.py; edit repositories.yaml, then regenerate. -->',
        '# Public repository inventory', '',
        'Canonical data: [repositories.yaml](repositories.yaml). This YAML file uses JSON syntax to keep generation dependency-free.', '',
        f'The 2026-10-06 card contained {scope["historical_card_count"]} entries. Public visibility was checked on {visibility_period}; {len(repos)} entries are included and {scope["excluded_count"]} excluded entries have no metadata here. Repository names do not establish visibility.', '',
        'Purpose descriptions retain the card’s original date. “Inferred” means summarized from README/name rather than a GitHub description. Primary language is current GitHub metadata, not a complete stack survey. Unarchived does not establish active development.', '',
        'CI below means workflow declarations at the recorded revision. PR triggers, branch/path filters and job conditions are retained in the canonical data; they do not prove that every PR gets functional checks. Required checks come from separate default-branch effective-rule and classic-protection queries. Empty checks mean observed none; null means unknown. App checks and hosted runtime results are not inventoried.', '',
        'Renovate fields record direct presets and local configuration only. Inherited preset resolution, organization defaults and actual bot behavior remain unknown. Shared references include local calls and calls to basher83/.github; other reusable calls remain visible in the workflow jobs.', '',
        '## Coverage', '',
        '| Field | Populated | Unknown / limit |',
        '| --- | ---: | --- |',
        f'| Public visibility, purpose, archive/fork flags, revision/date | {len(repos)} | Frameworks and development stage unknown for all |',
        f'| Primary language | {sum(r["stack"]["primary_language"] is not None for r in repos)} | {sum(r["stack"]["primary_language"] is None for r in repos)} unknown |',
        f'| Workflow declarations | {sum(r["ci"]["state"] == "observed" for r in repos)} | {sum(r["ci"]["state"] == "unknown" for r in repos)} unknown; {sum(r["ci"]["pr_workflow_declarations"] is True for r in repos)} declare PR triggers |',
        f'| Direct Renovate config | {sum(bool(r["renovate"]["configs"]) for r in repos)} present | {sum(r["renovate"]["state"] == "absent" for r in repos)} absent in searched paths; {sum(r["renovate"]["state"] == "unknown" for r in repos)} unknown; effective policy unknown for all |',
        f'| Required status checks | {sum(r["required_checks"]["state"] == "observed" for r in repos)} | {sum(r["required_checks"]["state"] == "unknown" for r in repos)} unknown; {sum(bool(r["required_checks"]["checks"]) for r in repos)} have required checks |',
        f'| Runtime results / approved adoption exceptions | 0 | {len(repos)} unknown |', '',
        '## Repositories', '',
        '| Repository | Lifecycle / fork | Primary language | Purpose (2026-10-06) | PR workflow declared | Required checks |',
        '| --- | --- | --- | --- | --- | --- |',
    ]
    for repo in repos:
        name = repo['repository']
        lifecycle = 'archived' if repo['lifecycle']['archived'] else 'unarchived'
        if repo['fork']:
            lifecycle += ', fork'
        purpose = repo['purpose']['text']
        if repo['purpose']['basis'] == 'inferred_from_readme_or_name':
            purpose += ' (inferred)'
        pr = {True: 'yes (declaration)', False: 'no', None: 'unknown'}[repo['ci']['pr_workflow_declarations']]
        values = [f'[{name.split("/", 1)[1]}](https://github.com/{name})', lifecycle, repo['stack']['primary_language'] or 'unknown', purpose, pr, required_label(repo)]
        lines.append('| ' + ' | '.join(cell(value) for value in values) + ' |')
    lines += ['', '## Configuration evidence', '', 'Dates and revisions below apply to file observations. Check requirements are mutable settings observed at that date, not properties of the Git revision.', '']
    for repo in repos:
        observed = repo['observation']
        lines += [f'### {repo["repository"]}', '', f'Observed {observed["observed_at"]}; [revision {observed["revision"][:12]}]({observed["evidence"]}). [Visibility API]({repo["visibility"]["evidence"]}).', '']
        configs = repo['renovate']['configs']
        if configs:
            for config in configs:
                presets = ', '.join(f'`{x}`' for x in config['extends']) or 'none'
                overrides = ', '.join(f'`{x}`' for x in sorted(config['local_overrides'])) or 'none'
                lines += [f'- Renovate [{config["path"]}]({config["evidence"]}): direct presets {presets}; local override fields {overrides}. Full values are in canonical data.']
        else:
            lines += [f'- Renovate: {repo["renovate"]["state"]} in searched config paths.']
        workflows = repo['ci']['workflows']
        if workflows:
            for workflow in workflows:
                triggers = ', '.join(f'`{event}`' for event in sorted(workflow['triggers'])) or 'none'
                lines.append(f'- Workflow [{workflow["path"]}]({workflow["evidence"]}): {triggers}. Filters and job conditions are in canonical data.')
        else:
            lines.append('- Workflows: unknown; file survey failed.' if repo['ci']['state'] == 'unknown' else '- Workflows: none in the observed default-branch workflow directory.')
        for ref in repo['ci']['shared_workflow_references']:
            lines.append(f'- Shared call ({ref["scope"]}): `{ref["reference"]}` from [{ref["caller"]}, job {ref["job"]}]({ref["evidence"]}).')
        if not repo['ci']['shared_workflow_references']:
            lines.append('- Central/local shared workflow calls: unknown; file survey failed.' if repo['ci']['state'] == 'unknown' else '- Central/local shared workflow calls: none observed in workflow jobs.')
        lint = repo['ci']['actionlint_references']
        lines.append('- actionlint references (scoped scan): ' + (', '.join(f'[{x["path"]}]({x["evidence"]})' for x in lint) if lint else ('unknown; file survey failed' if repo['ci']['state'] == 'unknown' else 'none observed')) + '.')
        lines.append(f'- Required checks: {required_label(repo)}. ' + ' '.join(f'[API evidence {i + 1}]({url})' for i, url in enumerate(repo['required_checks']['evidence'])) + '.')
        lines.append('')
    lines += ['## Historical observations', '']
    source_urls = {source['id']: source['url'] for source in data['sources']}
    for history in data['historical_observations']:
        lines.append(f'- {history["observed_date"]}, {history["repository"]}: {history["fact"]} {history.get("superseded_by", history.get("limits", ""))} [Historical source]({source_urls[history["source"]]}).')
    lines += ['', '## Proposals awaiting a separate decision', '', 'These are review candidates, not observed adoption, approved exceptions or authorization to migrate. CI duplication/equivalence with the central gate has not been evaluated. Approved exceptions remain unknown.', '']
    for proposal in data['proposals']:
        lines.append(f'- **{proposal["repository"]} ({proposal["type"]}):** {proposal["proposal"]} Basis: {proposal["basis"]} [Evidence]({proposal["evidence"]}).')
    lines += ['', '## Maintain this inventory', '',
        'Edit only `portfolio/repositories.yaml` for facts and proposals. Preserve historical dates and inference qualifiers; refresh public visibility before adding or publishing repository metadata. Remove entries that are no longer public. Add an immutable revision, observation date and evidence for new file facts; use null plus a reason when a query is blocked. Do not convert a missing config into a claim about bot installation or a CI declaration into a runtime pass.', '',
        'The initial survey searched default-branch `.github/workflows/*.{yml,yaml}`, root and `.github` `renovate.json/json5`, and root `mise.toml`, `.mise.toml`, `.pre-commit-config.yaml`, `hk.pkl` for actionlint references. Successful recursive-tree responses were checked for truncation; failed scans remain unknown. Refresh is manual; there is no recurring scanner.', '',
        'Run `python3 portfolio/inventory.py` to regenerate, `python3 portfolio/inventory.py --check` to validate freshness, and `python3 -m unittest discover -s portfolio -p "test_*.py"` for the publication and generation tests. `mise run ci` includes these checks alongside existing workflow linting.', '',
        'Validation guards the recorded visibility, provenance and generated output. It is offline and cannot establish that a repository remains public today; a fresh API visibility review is still needed before publication.', '',
        '## Sources', '',
    ]
    for source in data['sources']:
        lines.append(f'- [{source["id"]}]({source["url"]}), source observation date {source["observed_date"]}. {source.get("note", "")}')
    return '\n'.join(lines).rstrip() + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--directory', type=Path, default=Path(__file__).resolve().parent)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        data = validate(json.loads((args.directory / 'repositories.yaml').read_text()))
        overview = render(data)
        path = args.directory / 'README.md'
        if args.check:
            if not path.exists() or path.read_text() != overview:
                raise ValueError('Generated overview is stale; run python3 portfolio/inventory.py')
        else:
            path.write_text(overview)
        print(f'Validated {len(data["repositories"])} public repositories; overview {"current" if args.check else "generated"}.')
        return 0
    except (ValueError, KeyError, TypeError, OSError) as error:
        print(error, file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
